### ISSUE TITLE
Failed to load the atom-dynamic-macro package "Duplicate key 'ctrl-t'"

### ISSUE THREAD

**Issue by gpunktschmitz** [masui/atom-dynamic-macro#16]
1. install atom on linux
2. install the atom-dynamic-macro (using apm install)
3. on the next restart of atom the error appears

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Linux Mint
**Thrown From**: [atom-dynamic-macro](https://github.com/masui/atom-dynamic-macro) package, v1.2.0

### Stack Trace

Failed to load the atom-dynamic-macro package

```
At Duplicate key 'ctrl-t'

Error: Duplicate key 'ctrl-t'
  at Object.detectDuplicateKeys (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:268:13)
  at /usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at /usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at Obj (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/usr/share/atom/resources/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at /usr/share/atom/resources/app.asar/src/package.js:387:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/usr/share/atom/resources/app.asar/src/package.js:384:46)
  at /usr/share/atom/resources/app.asar/src/package.js:110:19
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:466:14)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:410:19
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:405:19)
  at /usr/share/atom/resources/app.asar/src/atom-environment.js:772:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dynamic-macro, v1.2.0 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by nandordena** [comment]
me 2
temporarily solved:

File > Setings > Keybindings > "your keymap file"
paste:

'.editor':
   'ctrl-t': 'atom-dynamic-macro:execute'

you do not need !unset this keybinding, just replace.

**Comment by ryoppippi** [comment]
**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [atom-dynamic-macro](https://github.com/masui/atom-dynamic-macro) package, v1.2.0


### Stack Trace

Failed to load the atom-dynamic-macro package

```
At Duplicate key 'ctrl-t'

Error: Duplicate key 'ctrl-t'
  at Object.detectDuplicateKeys (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:268:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at Obj (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:170:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:412:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:409:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:112:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:94:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:108:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:811:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "wrap-style",
      "advanced-open-file"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-beautify, v0.29.17 (inactive)
atom-dynamic-macro, v1.2.0 (inactive)
atom-jshint, v2.0.0 (inactive)
atom-material-syntax, v1.0.2 (inactive)
atom-material-syntax-light, v0.4.6 (inactive)
atom-material-ui, v1.3.9 (inactive)
atom-prettify, v0.1.3 (inactive)
atom-yeoman, v0.3.15 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-clang, v0.10.0 (inactive)
autocomplete-haskell, v0.7.2 (inactive)
autocomplete-paths, v1.0.5 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.5 (inactive)
compare-files, v0.8.0 (inactive)
emmet, v2.4.3 (inactive)
gist-it, v0.9.2 (inactive)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
gitignore-snippets, v0.2.5 (inactive)
haskell-ghc-mod, v1.19.6 (inactive)
highlight-selected, v0.12.0 (inactive)
ide-haskell, v1.9.3 (inactive)
ide-haskell-repl, v0.5.2 (inactive)
jquery-snippets, v11.0.0 (inactive)
json-schema, v0.1.15 (inactive)
jumpy, v3.1.3 (inactive)
language-haml, v0.24.1 (inactive)
language-haskell, v1.12.1 (inactive)
language-matlab, v0.2.1 (inactive)
language-swift, v0.5.0 (inactive)
linter, v1.11.22 (inactive)
linter-bootlint, v1.0.3 (inactive)
linter-clang, v3.4.6 (inactive)
linter-csslint, v1.3.3 (inactive)
linter-gcc, v0.7.1 (inactive)
linter-golinter, v1.2.1 (inactive)
linter-haml, v2.0.0 (inactive)
linter-hlint, v0.5.0 (inactive)
linter-javac, v1.9.4 (inactive)
linter-jscs, vundefined (inactive)
linter-less, v2.6.0 (inactive)
linter-lua, v1.0.2 (inactive)
linter-pylint, v1.2.2 (inactive)
linter-ruby, v1.2.4 (inactive)
linter-scalac, v1.4.2 (inactive)
linter-swiftc, v2.0.0 (inactive)
minimap, v4.26.8 (inactive)
minimap-autohide, v0.10.1 (inactive)
minimap-bookmarks, v0.4.2 (inactive)
minimap-pigments, v0.2.2 (inactive)
multi-cursor, v2.1.5 (inactive)
omnisharp-atom, v0.31.1 (inactive)
open-recent, v5.0.0 (inactive)
pdf-view, v0.54.0 (inactive)
pigments, v0.39.0 (inactive)
pretty-json, v1.6.1 (inactive)
processing-atom, v1.1.0 (inactive)
processing-autocomplete, v0.2.0 (inactive)
processing-language, v0.2.0 (inactive)
project-manager, v3.3.3 (inactive)
release-notes, v0.53.0 (inactive)
script, v3.14.1 (inactive)
show-ideographic-space, v1.0.2 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.3 (inactive)
symbols-tree-view, v0.13.2 (inactive)
sync-settings, v0.8.1 (inactive)
tab-numbers, v0.6.0 (inactive)
tag, v0.4.0 (inactive)
trailing-spaces, v0.4.0 (inactive)
tree-view-git-status, v1.3.0 (inactive)
tualo-git-context, v0.6.17 (inactive)
wrap-style, v0.3.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (inactive)
metrics, v1.1.3 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by gabor1** [comment]
just downloaded everything fresh, and this fix doesn't work for me... is this the latest fix?

**Comment by asicminer001** [comment]
same
