### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by shokai** [masui/atom-dynamic-macro#5]
[Enter steps to reproduce below:]
1. input `asdf\nasdf\n`
2. then press `ctrl+t`
3. got error

**Atom Version**: 1.5.2
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-dynamic-macro](https://github.com/masui/atom-dynamic-macro) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/sho/.atom/packages/atom-dynamic-macro/lib/atom-dynamic-macro.coffee:4

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.AtomDynamicMacro.execute (/Users/sho/.atom/packages/atom-dynamic-macro/lib/atom-dynamic-macro.coffee:4:3)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-dynamic-macro:execute (/Users/sho/.atom/packages/atom-dynamic-macro/lib/atom-dynamic-macro.coffee:9:94)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:13.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:04.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:00.6.0 atom-dynamic-macro:execute (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-dynamic-macro, v0.7.0

# Dev
No dev packages
```

**Comment by masui** [comment]
よくわからないがv0.8.0では大丈夫な模様
